### ISSUE TITLE
Looking for a new maintainer!

### ISSUE THREAD

**Issue by vinkla** [vinkla/laravel-gitlab#16]
I don't have the time to maintain this package any longer. If you want to take over the package, please let me know!

**Comment by antoniopaisfernandes** [comment]
😢

**Comment by jmverges** [comment]
Hi there, I could be involved. We use it at work

**Comment by Rubemlrm** [comment]
i can help . i use this at work =)

**Comment by marcpiresrj** [comment]
I can help too, I'm using at work and in play an important role with my integrations.

**Comment by vinkla** [comment]
Thanks everyone! I'm deprecating this package. You may use this package instead: [Laravel GitLab](https://github.com/GrahamCampbell/Laravel-GitLab).
