### ISSUE TITLE
Question: Usage Examples & Templates

### ISSUE THREAD

**Issue by Nowi5** [vinkla/laravel-gitlab#17]
Hi all,

I'm sorry to raise the question here, but I didn't saw any chat/forum.
Has somebody a package which delivers the typical controller and views like see, comment and create issues. Would be great to have this as an AdminLTE package 😉

Thank you.

**Comment by vinkla** [comment]
Hey @Nowi5, please use the GitHub issues for bugs, feature requests and other topics which could improve the project. Thanks.

**Comment by Nowi5** [comment]
If you would support a platform to discuss beside github I would use it. Any Slack channel, forum, chat?
Btw. that was a feature request: Please provide default views.

**Comment by vinkla** [comment]
> Btw. that was a feature request: Please provide default views.

This is Laravel wrapper around the
