### ISSUE TITLE
PHP 5.6 compatibility

### ISSUE THREAD

**Issue by CupOfTea696** [vinkla/laravel-gitlab#8]
Hi,

Just noticed that the ServiceProvider has a return type declaration, which is a PHP7 feature. Could this possibly be reverted? Laravel itself is still supporting PHP5.6 (for now). I'd revert to v2.5.5 but it's not L5.4 compatible...

Thanks,
Sven

**Comment by vinkla** [comment]
I get your point but I wanted to benefit from new changes in PHP 7.0 and decided to drop 5.6 from all my packages. 

> I’m well aware that requiring PHP 7 will hurt the popularity of our packages in the short run. But popularity is not our main goal. People who are using the latest and greatest version of PHP can benefit from our work. And I hope others will be nudged a bit towards PHP 7 by our decision.
>[Freek Van der Herten](https://murze.be/2016/01/why-we-are-requiring-php-7-for-our-new-packages)

Laravel 5.5 will most likely move to PHP 7.0 (probably in June or July 2017). We're just one step ahead in the release cycle. I suggest upgrading to PHP 7.0+ since there are huge benefits.

**Comment by CupOfTea696** [comment]
Well you could still have a release that's PHP5.6 + L5.4 and then have a release that's php 7?

**Comment by CupOfTea696** [comment]
Problem is we recently upgraded our servers to PHP5.6 (from 5.2 can you believe) where I work, I tried to push for PHP7 but it was only recently released back then and people didn't want to.

**Comment by vinkla** [comment]
I'm sorry but I wont release another version which is compatible with older versions of PHP. Try updating to PHP 7.0 or use Laravel 5.3 (nothing much changed between 5.3 and 5.4 really).
